---
title: "Idées"
author: "Projet ML"
date: "08/12/2017"
output: pdf_document
---

################################################################
#########################  DATA MINING  ########################
################################################################

Lien vers les donnees : https://www.divvybikes.com/system-data

Donnees sur les utilisations des velos en libre service dans la ville de Chicago
But : predire le nombre de velos dans chaque zone par demi-heure 

- regroupement par zone de population équivalente (FedStats) = variables en plus (socio, démo)
- minimiser erreur quadratique entre le nombre de vélos entrants, sortants d'une zone
- erreur relative selon les zones pour voir l'influence de la taille des stations
- visualisation temporelle (dynamique) pour voir les changements entre l'activité des zones pour 
la journée en semaine, le soir, le samedi et le dimanche (pourquoi pas les jours fériés)
- si changement de capacité au niveau des zones : prétraitement pour en tenir compte (on ne peut pas prévoir le changement de capacité)
- regarder les autres moyens de transport (taxis, bus, métros...)




- reprendre les donnees (faire un probleme plus simple)
